[install]
# Disable auto-install to prevent unexpected package installations
auto = false

# Use the fastest registry
registry = "https://registry.npmjs.org/"

# Optimize for development
dev = true

[install.cache]
# Enable caching for faster installs
disable = false

[run]
# Use bun's runtime by default
bun = true

# Enable hot reloading for development
hot = true 