name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Production Build
    runs-on: self-hosted
    environment: production

    strategy:
      matrix:
        node-version: [22.*]

    env:
      NODE_ENV: production
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      CHUTES_API_TOKEN: ${{ secrets.CHUTES_API_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DO_SPACES_BUCKET: ${{ secrets.DO_SPACES_BUCKET }}
      DO_SPACES_ENDPOINT: ${{ secrets.DO_SPACES_ENDPOINT }}
      DO_SPACES_REGION: ${{ secrets.DO_SPACES_REGION }}
      DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY }}
      DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      MUX_TOKEN_ID: ${{ secrets.MUX_TOKEN_ID }}
      MUX_TOKEN_SECRET: ${{ secrets.MUX_TOKEN_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install all dependencies
        run: npm ci --production=false

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run database migrations
        run: npx prisma migrate deploy

      - name: Build application
        run: npm run build

      - name: change dir and Deploy to production
        run: cd /home/ovveride/actions-runner/_work/lms-ali/lms-ali
        
      - name: change dir and Deploy to production
        run: 
          echo "Deploying to production..."
          pm2 restart p2s
